import { Match, StandingsResponse, TeamDetail, Competition } from '../types';

export const mockCompetitions: Competition[] = [
  {
    id: 2021,
    name: 'Premier League',
    code: 'PL',
    type: 'LEAGUE',
    emblem: 'https://crests.football-data.org/PL.png',
    area: { name: 'England', code: 'ENG', flag: 'https://crests.football-data.org/770.svg' },
  },
  {
    id: 2001,
    name: 'UEFA Champions League',
    code: 'CL',
    type: 'CUP',
    emblem: 'https://crests.football-data.org/CL.png',
    area: { name: 'Europe', code: 'EUR', flag: 'https://crests.football-data.org/EUR.svg' },
  },
  {
    id: 2014,
    name: 'La Liga',
    code: 'PD',
    type: 'LEAGUE',
    emblem: 'https://crests.football-data.org/laliga.png',
    area: { name: 'Spain', code: 'ESP', flag: 'https://crests.football-data.org/760.svg' },
  },
  {
    id: 2019,
    name: 'Serie A',
    code: 'SA',
    type: 'LEAGUE',
    emblem: 'https://crests.football-data.org/SA.png',
    area: { name: 'Italy', code: 'ITA', flag: 'https://crests.football-data.org/784.svg' },
  },
  {
    id: 2002,
    name: 'Bundesliga',
    code: 'BL1',
    type: 'LEAGUE',
    emblem: 'https://crests.football-data.org/BL1.png',
    area: { name: 'Germany', code: 'DEU', flag: 'https://crests.football-data.org/759.svg' },
  },
  {
    id: 2015,
    name: 'Ligue 1',
    code: 'FL1',
    type: 'LEAGUE',
    emblem: 'https://crests.football-data.org/FL1.png',
    area: { name: 'France', code: 'FRA', flag: 'https://crests.football-data.org/773.svg' },
  },
];

export function getMockMatches(): Match[] {
  const now = new Date();
  const todayStr = now.toISOString().split('T')[0];

  return [
    {
      id: 4001,
      utcDate: new Date(now.getTime() - 67 * 60000).toISOString(),
      status: 'IN_PLAY',
      minute: 68,
      matchday: 28,
      stage: 'REGULAR_SEASON',
      competition: mockCompetitions[0],
      homeTeam: {
        id: 65,
        name: 'Manchester City FC',
        shortName: 'Man City',
        tla: 'MCI',
        crest: 'https://crests.football-data.org/65.png',
      },
      awayTeam: {
        id: 57,
        name: 'Arsenal FC',
        shortName: 'Arsenal',
        tla: 'ARS',
        crest: 'https://crests.football-data.org/57.png',
      },
      score: {
        winner: null,
        duration: 'REGULAR',
        fullTime: { home: 2, away: 1 },
        halfTime: { home: 1, away: 1 },
      },
      extra: {
        referee: 'Michael Oliver',
        venue: 'Etihad Stadium, Manchester',
        attendance: 53400,
        stats: {
          possession: { home: 62, away: 38 },
          shotsTotal: { home: 14, away: 7 },
          shotsOnTarget: { home: 6, away: 3 },
          corners: { home: 8, away: 2 },
          fouls: { home: 9, away: 12 },
          yellowCards: { home: 1, away: 3 },
          redCards: { home: 0, away: 0 },
          saves: { home: 2, away: 4 },
          passes: { home: 512, away: 308 },
          passAccuracy: { home: 89, away: 81 },
        },
        events: [
          { minute: 18, type: 'GOAL', player: 'Erling Haaland', team: 'home', assist: 'Kevin De Bruyne' },
          { minute: 34, type: 'GOAL', player: 'Bukayo Saka', team: 'away', assist: 'Martin Ødegaard' },
          { minute: 58, type: 'GOAL', player: 'Phil Foden', team: 'home', assist: 'Bernardo Silva' },
          { minute: 61, type: 'YELLOW_CARD', player: 'Declan Rice', team: 'away' },
        ],
      },
    },
    {
      id: 4002,
      utcDate: new Date(now.getTime() - 32 * 60000).toISOString(),
      status: 'IN_PLAY',
      minute: 33,
      matchday: 28,
      stage: 'REGULAR_SEASON',
      competition: mockCompetitions[2],
      homeTeam: {
        id: 86,
        name: 'Real Madrid CF',
        shortName: 'Real Madrid',
        tla: 'RMA',
        crest: 'https://crests.football-data.org/86.png',
      },
      awayTeam: {
        id: 81,
        name: 'FC Barcelona',
        shortName: 'Barcelona',
        tla: 'FCB',
        crest: 'https://crests.football-data.org/81.png',
      },
      score: {
        winner: null,
        duration: 'REGULAR',
        fullTime: { home: 1, away: 1 },
        halfTime: { home: 1, away: 1 },
      },
      extra: {
        referee: 'Jesús Gil Manzano',
        venue: 'Santiago Bernabéu, Madrid',
        attendance: 81044,
        stats: {
          possession: { home: 49, away: 51 },
          shotsTotal: { home: 8, away: 9 },
          shotsOnTarget: { home: 4, away: 5 },
          corners: { home: 4, away: 5 },
          fouls: { home: 6, away: 7 },
          yellowCards: { home: 1, away: 1 },
          redCards: { home: 0, away: 0 },
          saves: { home: 4, away: 3 },
          passes: { home: 245, away: 260 },
          passAccuracy: { home: 87, away: 88 },
        },
        events: [
          { minute: 12, type: 'GOAL', player: 'Vinícius Júnior', team: 'home', assist: 'Jude Bellingham' },
          { minute: 29, type: 'GOAL', player: 'Robert Lewandowski', team: 'away', assist: 'Lamine Yamal' },
        ],
      },
    },
    {
      id: 4003,
      utcDate: new Date(now.getTime() - 82 * 60000).toISOString(),
      status: 'IN_PLAY',
      minute: 83,
      matchday: 27,
      stage: 'REGULAR_SEASON',
      competition: mockCompetitions[3],
      homeTeam: {
        id: 108,
        name: 'FC Internazionale Milano',
        shortName: 'Inter',
        tla: 'INT',
        crest: 'https://crests.football-data.org/108.png',
      },
      awayTeam: {
        id: 98,
        name: 'AC Milan',
        shortName: 'Milan',
        tla: 'MIL',
        crest: 'https://crests.football-data.org/98.png',
      },
      score: {
        winner: null,
        duration: 'REGULAR',
        fullTime: { home: 3, away: 2 },
        halfTime: { home: 2, away: 1 },
      },
      extra: {
        referee: 'Daniele Orsato',
        venue: 'San Siro, Milano',
        attendance: 75000,
        stats: {
          possession: { home: 54, away: 46 },
          shotsTotal: { home: 16, away: 11 },
          shotsOnTarget: { home: 7, away: 5 },
          corners: { home: 6, away: 4 },
          fouls: { home: 11, away: 14 },
          yellowCards: { home: 2, away: 4 },
          redCards: { home: 0, away: 1 },
          saves: { home: 3, away: 4 },
          passes: { home: 440, away: 370 },
          passAccuracy: { home: 86, away: 82 },
        },
        events: [
          { minute: 8, type: 'GOAL', player: 'Lautaro Martínez', team: 'home', assist: 'Nicolò Barella' },
          { minute: 23, type: 'GOAL', player: 'Rafael Leão', team: 'away', assist: 'Theo Hernández' },
          { minute: 44, type: 'GOAL', player: 'Marcus Thuram', team: 'home', assist: 'Federico Dimarco' },
          { minute: 67, type: 'GOAL', player: 'Christian Pulisic', team: 'away', assist: 'Tijjani Reijnders' },
          { minute: 76, type: 'GOAL', player: 'Lautaro Martínez', team: 'home', assist: 'Hakan Çalhanoğlu' },
          { minute: 80, type: 'RED_CARD', player: 'Fikayo Tomori', team: 'away' },
        ],
      },
    },
    {
      id: 4004,
      utcDate: new Date(now.getTime() - 150 * 60000).toISOString(),
      status: 'FINISHED',
      matchday: 28,
      stage: 'REGULAR_SEASON',
      competition: mockCompetitions[0],
      homeTeam: {
        id: 64,
        name: 'Liverpool FC',
        shortName: 'Liverpool',
        tla: 'LIV',
        crest: 'https://crests.football-data.org/64.png',
      },
      awayTeam: {
        id: 66,
        name: 'Manchester United FC',
        shortName: 'Man United',
        tla: 'MUN',
        crest: 'https://crests.football-data.org/66.png',
      },
      score: {
        winner: 'HOME_TEAM',
        duration: 'REGULAR',
        fullTime: { home: 3, away: 0 },
        halfTime: { home: 1, away: 0 },
      },
      extra: {
        referee: 'Anthony Taylor',
        venue: 'Anfield, Liverpool',
        attendance: 60100,
        events: [
          { minute: 35, type: 'GOAL', player: 'Luis Díaz', team: 'home', assist: 'Mohamed Salah' },
          { minute: 42, type: 'GOAL', player: 'Luis Díaz', team: 'home', assist: 'Mohamed Salah' },
          { minute: 56, type: 'GOAL', player: 'Mohamed Salah', team: 'home', assist: 'Dominik Szoboszlai' },
        ],
      },
    },
    {
      id: 4005,
      utcDate: new Date(now.getTime() + 120 * 60000).toISOString(),
      status: 'TIMED',
      matchday: 28,
      stage: 'REGULAR_SEASON',
      competition: mockCompetitions[4],
      homeTeam: {
        id: 5,
        name: 'FC Bayern München',
        shortName: 'Bayern',
        tla: 'FCB',
        crest: 'https://crests.football-data.org/5.png',
      },
      awayTeam: {
        id: 4,
        name: 'Borussia Dortmund',
        shortName: 'Dortmund',
        tla: 'BVB',
        crest: 'https://crests.football-data.org/4.png',
      },
      score: {
        winner: null,
        duration: 'REGULAR',
        fullTime: { home: null, away: null },
        halfTime: { home: null, away: null },
      },
      extra: {
        referee: 'Felix Zwayer',
        venue: 'Allianz Arena, München',
      },
    },
    {
      id: 4006,
      utcDate: new Date(now.getTime() + 240 * 60000).toISOString(),
      status: 'TIMED',
      matchday: 28,
      stage: 'REGULAR_SEASON',
      competition: mockCompetitions[1],
      homeTeam: {
        id: 524,
        name: 'Paris Saint-Germain FC',
        shortName: 'PSG',
        tla: 'PSG',
        crest: 'https://crests.football-data.org/524.png',
      },
      awayTeam: {
        id: 61,
        name: 'Chelsea FC',
        shortName: 'Chelsea',
        tla: 'CHE',
        crest: 'https://crests.football-data.org/61.png',
      },
      score: {
        winner: null,
        duration: 'REGULAR',
        fullTime: { home: null, away: null },
        halfTime: { home: null, away: null },
      },
      extra: {
        venue: 'Parc des Princes, Paris',
      },
    },
  ];
}

export function getMockStandings(leagueCode: string = 'PL'): StandingsResponse {
  const comp = mockCompetitions.find((c) => c.code === leagueCode) || mockCompetitions[0];

  const tableData: Array<{ name: string; short: string; tla: string; id: number; crest: string; p: number; w: number; d: number; l: number; gf: number; ga: number; pts: number; form: string }> = [
    { id: 65, name: 'Manchester City FC', short: 'Man City', tla: 'MCI', crest: 'https://crests.football-data.org/65.png', p: 28, w: 21, d: 4, l: 3, gf: 67, ga: 25, pts: 67, form: 'W,W,D,W,W' },
    { id: 64, name: 'Liverpool FC', short: 'Liverpool', tla: 'LIV', crest: 'https://crests.football-data.org/64.png', p: 28, w: 20, d: 5, l: 3, gf: 65, ga: 26, pts: 65, form: 'W,W,W,D,W' },
    { id: 57, name: 'Arsenal FC', short: 'Arsenal', tla: 'ARS', crest: 'https://crests.football-data.org/57.png', p: 28, w: 20, d: 4, l: 4, gf: 70, ga: 24, pts: 64, form: 'W,W,W,W,L' },
    { id: 58, name: 'Aston Villa FC', short: 'Aston Villa', tla: 'AVL', crest: 'https://crests.football-data.org/58.png', p: 28, w: 17, d: 4, l: 7, gf: 59, ga: 41, pts: 55, form: 'L,W,W,W,L' },
    { id: 73, name: 'Tottenham Hotspur FC', short: 'Tottenham', tla: 'TOT', crest: 'https://crests.football-data.org/73.png', p: 28, w: 16, d: 5, l: 7, gf: 59, ga: 42, pts: 53, form: 'W,L,W,D,W' },
    { id: 66, name: 'Manchester United FC', short: 'Man United', tla: 'MUN', crest: 'https://crests.football-data.org/66.png', p: 28, w: 15, d: 2, l: 11, gf: 39, ga: 39, pts: 47, form: 'W,W,L,L,W' },
    { id: 67, name: 'Newcastle United FC', short: 'Newcastle', tla: 'NEW', crest: 'https://crests.football-data.org/67.png', p: 28, w: 12, d: 4, l: 12, gf: 57, ga: 48, pts: 40, form: 'W,D,L,W,L' },
    { id: 61, name: 'Chelsea FC', short: 'Chelsea', tla: 'CHE', crest: 'https://crests.football-data.org/61.png', p: 28, w: 11, d: 6, l: 11, gf: 47, ga: 45, pts: 39, form: 'D,D,W,L,D' },
    { id: 512, name: 'West Ham United FC', short: 'West Ham', tla: 'WHU', crest: 'https://crests.football-data.org/512.png', p: 28, w: 11, d: 6, l: 11, gf: 45, ga: 50, pts: 39, form: 'L,W,W,L,D' },
    { id: 397, name: 'Brighton & Hove Albion FC', short: 'Brighton', tla: 'BHA', crest: 'https://crests.football-data.org/397.png', p: 28, w: 10, d: 9, l: 9, gf: 50, ga: 44, pts: 39, form: 'L,W,D,L,W' },
    { id: 76, name: 'Wolverhampton Wanderers FC', short: 'Wolves', tla: 'WOL', crest: 'https://crests.football-data.org/76.png', p: 28, w: 11, d: 5, l: 12, gf: 42, ga: 44, pts: 38, form: 'W,W,L,W,L' },
    { id: 62, name: 'Everton FC', short: 'Everton', tla: 'EVE', crest: 'https://crests.football-data.org/62.png', p: 28, w: 8, d: 7, l: 13, gf: 29, ga: 39, pts: 25, form: 'L,D,D,L,D' },
    { id: 63, name: 'Fulham FC', short: 'Fulham', tla: 'FUL', crest: 'https://crests.football-data.org/63.png', p: 28, w: 10, d: 5, l: 13, gf: 40, ga: 44, pts: 35, form: 'W,W,L,W,L' },
    { id: 1044, name: 'AFC Bournemouth', short: 'Bournemouth', tla: 'BOU', crest: 'https://crests.football-data.org/1044.png', p: 28, w: 8, d: 8, l: 12, gf: 37, ga: 49, pts: 32, form: 'D,W,L,D,L' },
    { id: 354, name: 'Crystal Palace FC', short: 'Crystal Palace', tla: 'CRY', crest: 'https://crests.football-data.org/354.png', p: 28, w: 7, d: 8, l: 13, gf: 33, ga: 48, pts: 29, form: 'D,L,W,D,L' },
    { id: 402, name: 'Brentford FC', short: 'Brentford', tla: 'BRE', crest: 'https://crests.football-data.org/402.png', p: 28, w: 7, d: 5, l: 16, gf: 39, ga: 52, pts: 26, form: 'L,D,L,L,D' },
    { id: 351, name: 'Nottingham Forest FC', short: 'Forest', tla: 'NFO', crest: 'https://crests.football-data.org/351.png', p: 28, w: 6, d: 7, l: 15, gf: 34, ga: 50, pts: 21, form: 'L,L,L,W,L' },
    { id: 389, name: 'Luton Town FC', short: 'Luton', tla: 'LUT', crest: 'https://crests.football-data.org/389.png', p: 28, w: 5, d: 6, l: 17, gf: 41, ga: 59, pts: 21, form: 'D,L,L,L,L' },
    { id: 328, name: 'Burnley FC', short: 'Burnley', tla: 'BUR', crest: 'https://crests.football-data.org/328.png', p: 28, w: 3, d: 5, l: 20, gf: 27, ga: 62, pts: 14, form: 'D,L,L,L,L' },
    { id: 356, name: 'Sheffield United FC', short: 'Sheffield Utd', tla: 'SHU', crest: 'https://crests.football-data.org/356.png', p: 28, w: 3, d: 5, l: 20, gf: 24, ga: 74, pts: 14, form: 'D,L,L,L,W' },
  ];

  return {
    competition: comp,
    season: {
      id: 2026,
      startDate: '2025-08-15',
      endDate: '2026-05-25',
      currentMatchday: 28,
    },
    standings: [
      {
        stage: 'REGULAR_SEASON',
        type: 'TOTAL',
        group: null,
        table: tableData.map((item, idx) => ({
          position: idx + 1,
          team: {
            id: item.id,
            name: item.name,
            shortName: item.short,
            tla: item.tla,
            crest: item.crest,
          },
          playedGames: item.p,
          form: item.form,
          won: item.w,
          draw: item.d,
          lost: item.l,
          points: item.pts,
          goalsFor: item.gf,
          goalsAgainst: item.ga,
          goalDifference: item.gf - item.ga,
        })),
      },
    ],
  };
}

export function getMockTeamDetail(teamId: number): TeamDetail {
  return {
    id: teamId,
    name: 'Manchester City FC',
    shortName: 'Man City',
    tla: 'MCI',
    crest: 'https://crests.football-data.org/65.png',
    address: 'Etihad Campus, Manchester M11 3FF',
    website: 'https://www.mancity.com',
    founded: 1880,
    clubColors: 'Sky Blue / White',
    venue: 'Etihad Stadium',
    coach: {
      id: 1160,
      name: 'Pep Guardiola',
      nationality: 'Spain',
    },
    squad: [
      { id: 1, name: 'Ederson', position: 'Goalkeeper', shirtNumber: 31, nationality: 'Brazil' },
      { id: 2, name: 'Stefan Ortega', position: 'Goalkeeper', shirtNumber: 18, nationality: 'Germany' },
      { id: 3, name: 'Rúben Dias', position: 'Defence', shirtNumber: 3, nationality: 'Portugal' },
      { id: 4, name: 'John Stones', position: 'Defence', shirtNumber: 5, nationality: 'England' },
      { id: 5, name: 'Nathan Aké', position: 'Defence', shirtNumber: 6, nationality: 'Netherlands' },
      { id: 6, name: 'Josko Gvardiol', position: 'Defence', shirtNumber: 24, nationality: 'Croatia' },
      { id: 7, name: 'Kyle Walker', position: 'Defence', shirtNumber: 2, nationality: 'England' },
      { id: 8, name: 'Rodri', position: 'Midfield', shirtNumber: 16, nationality: 'Spain' },
      { id: 9, name: 'Kevin De Bruyne', position: 'Midfield', shirtNumber: 17, nationality: 'Belgium' },
      { id: 10, name: 'Bernardo Silva', position: 'Midfield', shirtNumber: 20, nationality: 'Portugal' },
      { id: 11, name: 'Mateo Kovacic', position: 'Midfield', shirtNumber: 8, nationality: 'Croatia' },
      { id: 12, name: 'Phil Foden', position: 'Midfield', shirtNumber: 47, nationality: 'England' },
      { id: 13, name: 'Erling Haaland', position: 'Offence', shirtNumber: 9, nationality: 'Norway' },
      { id: 14, name: 'Jérémy Doku', position: 'Offence', shirtNumber: 11, nationality: 'Belgium' },
      { id: 15, name: 'Jack Grealish', position: 'Offence', shirtNumber: 10, nationality: 'England' },
    ],
  };
}
